service: ghost-api

plugins:
  - serverless-python-requirements

package:
  exclude:
    - ./**
  include:
    - ./src/**

provider:
  name: aws
  runtime: python3.8
  timeout: 5
  environment:
    GHOST_GAMES_TABLE_NAME: !Ref GamesTable
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DescribeTable
      Resource:
        - { "Fn::GetAtt": ["GamesTable", "Arn"] }


functions:
  api:
    description: 2D Ghost REST API
    handler: src.ghost_api.api.handler
    memorySize: 128
    maximumRetryAttempts: 0
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY


resources:
  Resources:
    # DynamoDB tables
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ghost-games-table-${opt:stage}
        KeySchema:
          - AttributeName: room_code
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: room_code
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
