name: CI
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install docker on MacOS
      run:   |
         if [ "$RUNNER_OS" == "macOS" ]; then
            brew install docker docker-machine docker-compose
         fi
      shell: bash
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4
    - name: Install project
      run: poetry install
    - name: Lint
      run: poetry run poe lint
    - name: Test
      run: poetry run poe test
