name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1.0.1
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage ${BRANCH_NAME}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET_KEY }}
  